## Example code to load BERT word embedding files

In [1]:
import pickle
import pandas as pd
chunk_len = 512
fname = 'data/distilBert_embeddings_olap_' + str(chunk_len) + '.pkl'

with open(fname, 'rb') as fp:
    df_olap = pickle.load(fp)

In [2]:
df_olap.head()

,docid,label,doc_use,input_ids_np_olap,embeddings
0,73277,0,train,"[101, 5650, 122, 1128, 1132, 4601, 1112, 3226,...","[0.25269353, -0.012546801, -0.18077362, -0.207..."
1,73277,0,train,"[101, 19073, 2861, 1108, 5528, 1165, 1131, 176...","[0.29047894, -0.028722603, -0.18684211, -0.158..."
2,73277,0,train,"[101, 1108, 3950, 10361, 1223, 15597, 1106, 11...","[0.40752962, -0.01768893, -0.2188747, -0.27248..."
3,73277,0,train,"[101, 1216, 6969, 1412, 6015, 1482, 1538, 1129...","[0.37521833, 0.065477476, -0.31785288, -0.2426..."
4,73277,0,train,"[101, 123, 1128, 1127, 1107, 1231, 20993, 1121...","[0.4149907, 0.08175331, -0.18540347, -0.214996..."

In [3]:
fname = 'data/distilBert_embeddings_headtail_' + str(chunk_len) + '.pkl'

with open(fname, 'rb') as fp:
    df_headtail = pickle.load(fp)

In [4]:
df_headtail.head()

,docid,text,label,len_txt,doc_use,input_ids_np_head,input_ids_np_tail,head_embeddings,tail_embeddings
0,73277,sentence 1 you are charged as follows first co...,0,1853,train,"[101, 5650, 122, 1128, 1132, 4601, 1112, 3226,...","[101, 2456, 178, 1546, 1142, 5650, 1106, 1576,...","[0.25269353, -0.012546801, -0.18077362, -0.207...","[0.2996538, 0.03536769, -0.2073312, -0.2582946..."
1,79776,sentence 1 josefa kotobalavu you were charged ...,1,448,train,"[101, 5650, 122, 179, 6787, 8057, 180, 12355, ...","[101, 1105, 6616, 1128, 1444, 1106, 1129, 1549...","[0.37055653, 0.0945884, -0.2691407, -0.2511654...","[0.39960948, 0.036339585, -0.19816011, -0.2828..."
2,75870,sentence 1 the director of public prosecution ...,1,2995,train,"[101, 5650, 122, 1103, 1900, 1104, 1470, 12369...","[101, 1128, 1132, 2198, 1228, 15981, 171, 1128...","[0.546021, -0.026345802, -0.17009248, -0.27585...","[0.30198795, 0.05779965, -0.2539207, -0.289445..."
3,79299,sentence 1 mohommed nabi ud dean you were conv...,1,339,train,"[101, 5650, 122, 182, 10559, 4165, 4611, 9468,...","[101, 1673, 6408, 20261, 185, 7409, 2646, 1182...","[0.41824618, 0.0206348, -0.32047457, -0.267952...","[0.12322511, 0.066628575, 0.19230752, -0.41416..."
4,80603,judgment of the court background 1 the appella...,0,2937,train,"[101, 9228, 1104, 1103, 2175, 3582, 122, 1103,...","[101, 1195, 1132, 8723, 1115, 1103, 1546, 1674...","[0.38705596, -0.020253679, -0.30580142, -0.270...","[0.36908972, 0.029414382, -0.2629541, -0.27822..."